name: Commit Lint - Conventional Commits

on: [pull_request]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
